### ISSUE TITLE
Indentation issue: nested hashes

### ISSUE THREAD

**Issue by darkfeline** [voxpupuli/puppet-mode#108]
Puppet Mode version: 20170928.1007

1. Got

``` puppet
class foo {
  $x = deep_merge($y,
  {
    'X' => {
      'y' => 'z',
    },
  }
)
}
```

expected

``` puppet
class foo {
  $x = deep_merge($y,
    {
      'X' => {
        'y' => 'z',
      },
    }
  )
}
```

2. Got

``` puppet
class foo {
  $x = deep_merge($y, {
    'X' => {
      'y' => 'z',
    },
    })
}
```

expected

``` puppet
class foo {
  $x = deep_merge($y, {
    'X' => {
      'y' => 'z',
    },
  })
}
```

**Comment by paran1** [comment]
Not what I wrote it for, but #104 makes the indentation of the second example be as you prefer, du to the closing brace being detected correctly.

However, both example highlighs a general problem with indentation of function arguments, unrelated to hashes. You can show the same thing like this (indented by puppet-mode):

    class foo {
      $bar = any_function($x,
      $y, $z)
    }

I would actually prefer if puppet-mode did what most other language modes do and indented like this:

    class foo {
      $bar = any_function($x,
                          $y, $z)
    }

Note that this would indent the first example like this:

    class foo {
      $x = deep_merge($y,
                      {
                        'X' => {
                          'y' => 'z',
                        },
                      }
      )
    }

**Comment by KedneckInc** [comment]
From the header comments of puppet-mode.el

```
Package-Version: 20171220.2249
Version: 0.4-cvs
```

```
Emacs Version: 25.3.1
```

**Summary**: Every time there's a hash nested inside an array, the indentation slides one to the right.

Post Indent Region:

```
someresource { 'foobar':
  ensure      => 'present',
  alpha       => [
    {
      'value' => 'beta',
      'href'  => 'gamma',
    },
  ],
    delta     => 120,
    zulu       => [
      {
        'value' => 'yankey',
        'href'  => 'xeno',
      },
    ],
      morph     => 120,
}
```

Expected:

```
someresource { 'foobar':
  ensure      => 'present',
  alpha       => [
    {
      'value' => 'beta',
      'href'  => 'gamma',
    },
  ],
  delta     => 120,
  zulu       => [
    {
      'value' => 'yankey',
      'href'  => 'xeno',
    },
  ],
  morph     => 120,
}
```
