### ISSUE TITLE
Frequent Travis check failures

### ISSUE THREAD

**Issue by paran1** [voxpupuli/puppet-mode#109]
On my last three pull requests (#105, #106, #107) the Travis checks failed for one or more emacs versions. All were false alarms, and failed due to cask not being able to download archives. Example output:

    $ cask install
    Importing package-keyring.gpg...
    Importing package-keyring.gpg...done
    Contacting host: melpa.org:443
    Opening TLS connection to ‘melpa.org’...
    Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 melpa.org’...
    Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 melpa.org’...failed
    Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 melpa.org --protocols ssl3’...
    Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 melpa.org --protocols ssl3’...failed
    Opening TLS connection to ‘melpa.org’...failed
    Failed to download ‘melpa’ archive.
    Contacting host: elpa.gnu.org:443
    Opening TLS connection to ‘elpa.gnu.org’...
    Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 elpa.gnu.org’...
    Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 elpa.gnu.org’...failed
    Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 elpa.gnu.org --protocols ssl3’...
    Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/certs/ca-certificates.crt -p 443 elpa.gnu.org --protocols ssl3’...failed
    Opening TLS connection to ‘elpa.gnu.org’...failed
    Package refresh done
    Failed to download ‘gnu’ archive.
    Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
    Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
    Package ‘s-’ is unavailable
    
    The command "cask install" failed and exited with 255 during .

I am new to using Travis CI. A quick online search suggest that there is a command called `travis_retry` that might be able to help.

**Comment by rski** [comment]
https://github.com/voxpupuli/puppet-mode/pull/131 I wanna say this will make things slightly better, because fewer things will have to be done up to the point where melpa becomes available. I remember there were some issues with s- going away at some point too.
