### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by anarcat** [voxpupuli/puppet-mode#117]
the last release here is 5 years old, and there seems to have been much work done since then. could we tag a new release? this would be useful for the [Debian packaging work in progress](https://bugs.debian.org/923899).

thanks!

**Comment by bastelfreak** [comment]
Hi @anarcat, this repository got migrated to us and I'm not very familiar with Emacs. Do you just require a new git tag?

**Comment by anarcat** [comment]
yep!

**Comment by anarcat** [comment]
ping! can we get a new tag here? 0.4 would do. ;) i'd be happy to push one to my fork if that helps...

**Comment by sten0** [comment]
@bastelfreak, gentle ping to please tag a release at your earliest convenience.  +1 on version 0.4, because a 0.3.1 isn't significant enough to indicate a change of maintainer IMHO.  On that topic, modify the following lines to accurately define the current maintainer[s] before tagging a new release https://github.com/voxpupuli/puppet-mode/blob/7dee1b5a5debac6e56f9107492a413b6c0edb94d/puppet-mode.el#L10-L11

Thank you for maintaining `puppet-mode`!  P.S. I maintain the Debian package :-)

**Comment by sten0** [comment]
Also, it looks like 0.4 is what the previous maintainers intended:
https://github.com/voxpupuli/puppet-mode/blob/7dee1b5a5debac6e56f9107492a413b6c0edb94d/puppet-mode.el#L14

It might also be a good idea to drop the `-cvs` suffix before tagging ;-)

**Comment by sten0** [comment]
@voxpupuli, @pccibot, @bastelfreak 

Gentle ping for the new version.  See https://github.com/voxpupuli/puppet-mode/issues/117#issuecomment-509805652 and https://github.com/voxpupuli/puppet-mode/issues/117#issuecomment-509806722 for trivially easy changes that should be made before tagging the release.

**Comment by bastelfreak** [comment]
@sten0 can you provide patches for that?

**Comment by sten0** [comment]
Done, at #121.  Could you take care of checking my work on CHANGES.md and continuing to update it with the history since 0.3?

**Comment by sten0** [comment]
P.S. @anarcat if bastelfreak needs help with CHANGES.md today, and if you're free, could you finish the remaining ~30% of work?  I need a break :-)

**Comment by anarcat** [comment]
> P.S. @anarcat if bastelfreak needs help with CHANGES.md today, and if you're free, could you finish the remaining ~30% of work? I need a break :-)

I'm confused: how do you expect me to do that with your existing PR?

not knowing any better way, i took your branch and finished the `CHANGES` changes and pushed to a new PR, in #122.

**Comment by anarcat** [comment]
@bastelfreak would love to release this, but i don't have the credentials to push, i believe. would you mind doing the honors or sharing the wealth? :)

**Comment by anarcat** [comment]
actually, i can push tags too, so this is done. :)
