### ISSUE TITLE
Update the project description?

### ISSUE THREAD

**Issue by mmuehlenhoff** [voxpupuli/puppet-mode#124]
It currently reads "Edit Puppet 3 manifests with GNU Emacs 24", which makes it sound a little dated, given that modern Emacs variants and Puppet up to 5 are supported, how about "Edit Puppet (3-5) manifests with GNU Emacs"? instead

**Comment by ekohl** [comment]
I've dropped the number altogether. The README is clear about the versions and Puppet 2 is really dead. I personally don't use this project so I'm happy if anyone else can have a better look.

**Comment by sebastianrakel** [comment]
I'm using it every day for my puppet work up to puppet 6 and it's working fine.

So maybe i would change the versions to "Puppet 3 and newer Manifests with GNU Emacs 24 and newer"

**Comment by ekohl** [comment]
I consider Puppet 2 and older dead so I don't really see the added value. Closing and considering it done.
