### ISSUE TITLE
indentation with {}

### ISSUE THREAD

**Issue by cwage** [voxpupuli/puppet-mode#67]
Can anyone help me understand why this is happening? While editing a puppet manifest, i highlight the region with shift-v, y p to yank and paste and it strips a layer of tab indentation out when i paste:

![selection_171](https://cloud.githubusercontent.com/assets/190973/19047307/dfbcabbc-8966-11e6-93a0-c9cdac4ee843.png)

I am not sure if this is a bug or something I'm doing wrong. If it helps, if I change those curly braces to brackets (just to test), I don't get that behaviour and it pastes fine.

**Comment by rski** [comment]
@cwage  Can you post a bit more of the surrounding manifest so that I can replicate this? Foobaring values that you don't want to is perfectly fine of course, I just need the structure of the resources that enclose this.

**Comment by cwage** [comment]
@rski sure thing -- attached is a file that exhibits this behaviour:

[config.pp.txt](https://github.com/voxpupuli/puppet-mode/files/579357/config.pp.txt)

**Comment by rski** [comment]
oops I completely forgot about this, sorry.

**Comment by cwage** [comment]
fwiw I am still having this problem -- not 100% sure i have the version with this fix, though?

spacemacs currently has elpa/puppet-mode-20170928.1007/
