### ISSUE TITLE
Drop <emacs 24.4 support

### ISSUE THREAD

**Issue by rski** [voxpupuli/puppet-mode#72]
There are some macros defined to make puppet-mode work for emacs 24.2. There might be some other stuff too I didn't notice.
Since the tests run for emacs 24.4 and above imo there is no point in keeping them around.

**Comment by bbatsov** [comment]
24.4 is relatively new, so that might not be a great idea (unless it's warranted by something important - like SMIE support).

**Comment by rski** [comment]
The point about newness is true. I was thinking about SMIE support basically, yes.
If you don't want to drop the support, we can just leave this as a reminder, like flycheck has the issue about dropping emacs 24 support.

**Comment by lunaryorn** [comment]
> 24.4 is relatively new

Emacs 24.4 is two(!) years old… that's "new" in Emacs-land?

That said, I'm not for dropping older versions just to get rid of some compatibility definitions that were copied from upstream.  I would however if we can profit from new APIs in Emacs 24.4 that are difficult to define.

**Comment by rski** [comment]
>I would however if we can profit from new APIs in Emacs 24.4 that are difficult to define.
like SMIE?

**Comment by lunaryorn** [comment]
If SMIE is 24.4 only then yes.  But that's not my decision anymore soon… I'll be moving the repo and stepping down from maintenance.

**Comment by smoeding** [comment]
Emacs 25.1 is almost 5(!) years old (released on 2016-09-17) so maybe the time has come to start dropping support for Emacs 24?

**Comment by kenyon** [comment]
> Emacs 25.1 is almost 5(!) years old (released on 2016-09-17) so maybe the time has come to start dropping support for Emacs 24?

:+1:

**Comment by rski** [comment]
I'm a bit torn. Packages like ivy seem to require emacs 24.5 I would be ok with removing emacs 24.5 from the CI matrix and accepting any fixes for older emacsen .

**Comment by rski** [comment]
https://github.com/voxpupuli/puppet-mode/pull/131 for dropping emacs 24 from the CI. I think supporting the last 3 major release trains is more than enough.

**Comment by rski** [comment]
I'll consider this fixed for now. I won't work on explicitly removing support for now, but I'll try to have a look soon at the xref request that needs emacs > 25.
