### ISSUE TITLE
Emacs freeze on indent

### ISSUE THREAD

**Issue by XANi** [voxpupuli/puppet-mode#77]
version elpa 20161204.713, also tested on bfa9512

when trying to indent last line:

    define core::vm
    (
        $disk = false,
        $interfaces,
        $vcpu = 4,
        $mem = 1024,
        $firewall = false,
        $vnc_port = false,
        $vnc_pass = false,
        $vnc_ip = undef,
        $ceph_config = false,
        )  {

emacs 25.1 freezes and uses 100% CPU when I go to last line and press enter or tab, SIGUSR2 unfrezes it with trace:

    Debugger entered--entering a function:
    * command-error-default-function((quit) "" nil)
      recursive-edit()
      debug(error (quit))
      looking-at(" ?class +.*?($")
      puppet-indent-line()
      indent-according-to-mode()
      electric-indent-post-self-insert-function()
      self-insert-command(1)
      newline(nil 1)
      funcall-interactively(newline nil 1)
      call-interactively(newline nil nil)
      command-execute(newline)

or (on `emacs -Q`) 

    Debugger entered--Lisp error: (quit)
      looking-at(" ?class +.*?($")
      puppet-indent-line()
      indent-for-tab-command(nil)
      funcall-interactively(indent-for-tab-command nil)
      call-interactively(indent-for-tab-command nil nil)
      command-execute(indent-for-tab-command)

I've tested it with emacs -Q and without and just puppet-mode loaded, 

If I have bisected it correctly version elpa 20161204.713, also tested on bfa9512

when trying to indent last line:

    define core::vm
    (
        $disk = false,
        $interfaces,
        $vcpu = 4,
        $mem = 1024,
        $firewall = false,
        $vnc_port = false,
        $vnc_pass = false,
        $vnc_ip = undef,
        $ceph_config = false,
        )  {

emacs 25.1 freezes and uses 100% CPU when I go to last line and press enter or tab, SIGUSR2 unfrezes it with trace:

    Debugger entered--entering a function:
    * command-error-default-function((quit) "" nil)
      recursive-edit()
      debug(error (quit))
      looking-at(" ?class +.*?($")
      puppet-indent-line()
      indent-according-to-mode()
      electric-indent-post-self-insert-function()
      self-insert-command(1)
      newline(nil 1)
      funcall-interactively(newline nil 1)
      call-interactively(newline nil nil)
      command-execute(newline)

or (on `emacs -Q`) 

    Debugger entered--Lisp error: (quit)
      looking-at(" ?class +.*?($")
      puppet-indent-line()
      indent-for-tab-command(nil)
      funcall-interactively(indent-for-tab-command nil)
      call-interactively(indent-for-tab-command nil nil)
      command-execute(indent-for-tab-command)

I've tested it with emacs -Q and without and just puppet-mode loaded, 

If I have bisected it correctly, 3321cd2 is causing it and 268ec79 is last good

**Comment by rski** [comment]
woah, thanks for this great bug report. Hopefully i'll get around to fixing this during the weekend.

**Comment by rski** [comment]
or if you want to do it, @XANi, that would be amazing

**Comment by XANi** [comment]
Sorry , I don't know emacs (or lisp for that matter) very well, the most I did with syntax is plug a bunch of keywords into [generic mode](https://github.com/XANi/config/blob/master/modules/emacs/files/parts/haproxy-mode.el) so

**Comment by rski** [comment]
This works now \o/
