### ISSUE TITLE
Fix puppet debugger integration

### ISSUE THREAD

**Issue by rski** [voxpupuli/puppet-mode#82]
puppet debugger's command has changed from `pdb` (which is good because that is the widely used python debugger) to `puppet debugger`.
This needs to be changed in puppet-mode, 
I've tried, but make-comint doesn't seem to like the space in the command much, so'll look into it a bit more soon.

**Comment by logicminds** [comment]
I can make a new command called puppet-debugger if that helps. Open to suggestions.

**Comment by rski** [comment]
I don't want to put an burden on you, I have some time this week and hopefully i'll fix it on our side. Heck, it could even be an issue with my environment.

**Comment by rski** [comment]
This exposed another bug with the way puppet-mode starts the repl, this is great. We really should add tests for starting the repl though.

**Comment by logicminds** [comment]
Note: https://github.com/nwops/puppet-debugger/issues/49

I'll be fixing this in 0.5.0 release.  There is also a  big difference between `pdb` and `puppet debugger`.  Basically the two commands startup puppet differently with regards to the puppet environment.  With the puppet debugger command you can pass in normal puppet command flags, pull in real facts with `--no-facterdb`


On a side note it would also be interesting to see how the `debug::break()` function integrates with emacs for live debugging.  This would setup a breakpoint and allow you to check variables. 
Which is similar to `binding.pry` if you use pry.

**Comment by rski** [comment]
oh, that could be interesting, adding an interface for gud/realgud and such

**Comment by rski** [comment]
@logicminds I worked it out and also got to learn a few useful things in the process too :-D

**Comment by logicminds** [comment]
Not exactly sure if this would work but I think if the main debugger command is `puppet` and the rest are args for the puppet command like `['debugger']`

or ['debugger', '--play', 'some_manifest.pp'] this might be how you integrate the two.

**Comment by rski** [comment]
yup, that is pretty much what I implemented
